pipeline {
    agent any
    tools {
        maven 'maven_3_8_1'
        jdk 'jdk_17'
    }
    stages {
        stage('Build maven') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/NicolasAMunozR/TingesoLab1-Backend']])
                dir('backend') { // Cambia a la carpeta 'backend'
                    bat 'mvn clean package' // Ejecuta Maven en la subcarpeta
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('backend') { // Cambia a la carpeta 'backend' donde está el pom.xml
                    bat 'mvn test' // Ejecuta las pruebas unitarias
                }
            }
        }

        stage('Build docker image') {
            steps {
                script {
                    dir('backend') { // Cambia a la carpeta 'backend' para construir la imagen Docker
                        bat 'docker build -t nickasch/backend:latest .' // Construye la imagen en la subcarpeta
                    }
                }
            }
        }
        
        stage('Push image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'tingeso', variable: 'dhpsw')]) {
                        bat 'docker login -u nickasch -p %dhpsw%'
                    }
                    bat 'docker push nickasch/backend:latest' // Empuja la imagen a Docker Hub
                }
            }
        }
    }
}
